### ISSUE TITLE
What are "Processes"?

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#270]
#### Page Path

Exponential-e
http://5.148.81.153:7080/ui/Server_Monitors_Processes
#### Description of Issue

In the screenshot below, the top row is processes.  What is this data?
![image](https://cloud.githubusercontent.com/assets/18315382/19772728/19b61b88-9c35-11e6-91f5-12e8698b9b24.png)

**Comment by DmitryIsakbayev** [comment]
I think it is the new Share Shield application.  I will add it to the FileMon.etc configuration.

**Comment by DmitryIsakbayev** [comment]
Please test.

**Comment by JimDalton** [comment]
Fixed on .32.  Thank you

**Comment by DmitryIsakbayev** [comment]
The issue still existed for SDReporter.  The paths.view in /ui/Server_Monitors_Processes page was missing `&filterKey=.*Summary.*` parameter.
